[workspace]

members = [
    "abc",
    "arc",
    "agc",
    "ahc",
    "typical-dp",
    "edpc",
    "typical90",
    "atcoder-other-contests",
    "snippet",
    "aoj",
    "yukicoder",
    "codeforces",
    "books",
    "work"
]
